services:
  cyberjawara:
    container_name: 5-LPT
    build: 
      context: .
    restart: always
    ports:
      - "127.0.0.1:10001:9999"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
