services:
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 13371:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bot
      - note
    networks:
      - internal
  note:
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - internal
  bot:
    build:
      context: bot
      args:
        - BROWSER=
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://note:5000
      # only allow hex
      APPURLREGEX: ^http://note:5000/workspace/display/[0-9a-f]{25}$
      APPFLAG: CJ{0ne_sho0t_0n3_k1ll}
      APPLIMIT: 5
      # please solve it locally first
      APPLIMITTIME: 3600
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    networks:
      - internal
      # uncoment this if you need to run the bot in GUI mode
      # run this before running the docker container if you're use xauth `sudo xhost +local:docker`
      # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  internal:
